---
noname:
  # Noname Deployment Domain from Security & Compliance settings
  host_name: noname_domain
  # Service account credentials
  client_id: xxxxxx
  client_secret: xxxxxx

discovery:
  datasource_name: ibmsec-data-source 
  platform_api_prefix: platform-api
  apic_host_domain: us-east-a.apiconnect.automation.ibm.com
  provider_org: myOrgName
  api_key: xxxxxx
  namespace: default

logging:
  log_level: debug

images:
  api_discovery_noname_collector: ghcr.io/ibm-apiconnect/api-discovery-noname-collector:40-2025-11-05-06-41-14
